import type {
  PreparedAnalyticsData,
  PreparedRunRow,
  PreparedSessionReviewV2Row,
  ReviewerRuntimeReference,
} from '../scripts/contracts.ts';

/** Build a minimal PreparedRunRow with sensible defaults for actionability tests. */
export function makeRun(overrides: Partial<PreparedRunRow> & { runId: string; modelId: string }): PreparedRunRow {
  return {
    runId: overrides.runId,
    taskGroupId: overrides.taskGroupId ?? `${overrides.runId}-task`,
    sessionId: overrides.sessionId ?? `session-${overrides.runId}`,
    identityFallback: overrides.identityFallback ?? false,
    sessionPathHash: overrides.sessionPathHash ?? `hash-${overrides.runId}`,
    harnessRevision: overrides.harnessRevision ?? null,
    harnessFingerprint: overrides.harnessFingerprint ?? null,
    harnessStatus: overrides.harnessStatus ?? 'current',
    isCurrentHarness: overrides.isCurrentHarness ?? true,
    status: overrides.status ?? 'closed',
    startedAt: overrides.startedAt ?? '2026-05-10T12:00:00.000Z',
    startedDay: overrides.startedDay ?? '2026-05-10',
    updatedAt: overrides.updatedAt ?? '2026-05-10T12:00:00.000Z',
    finalizedAt: overrides.finalizedAt ?? '2026-05-10T12:00:00.000Z',
    finalizationReason: overrides.finalizationReason ?? 'closed',
    modelId: overrides.modelId,
    modelFamily: overrides.modelFamily ?? overrides.modelId,
    provider: overrides.provider ?? null,
    thinkingLevel: overrides.thinkingLevel !== undefined ? overrides.thinkingLevel : 'high',
    mixedModelConfig: overrides.mixedModelConfig ?? false,
    mixedTreatmentConfig: overrides.mixedTreatmentConfig ?? false,
    experimentAssignment: overrides.experimentAssignment ?? null,
    promptFamily: overrides.promptFamily ?? null,
    promptHashPrefix: overrides.promptHashPrefix ?? null,
    promptCapturedAt: overrides.promptCapturedAt ?? null,
    toolSetHashPrefix: overrides.toolSetHashPrefix ?? null,
    skillSetHashPrefix: overrides.skillSetHashPrefix ?? null,
    skillEntries: overrides.skillEntries ?? [],
    activeExtensions: overrides.activeExtensions ?? [],
    selectedToolCount: overrides.selectedToolCount ?? 0,
    skillCount: overrides.skillCount ?? 0,
    contextFileCount: overrides.contextFileCount ?? 0,
    promptGuidelineCount: overrides.promptGuidelineCount ?? 0,
    initialUserMessageChars: overrides.initialUserMessageChars !== undefined ? overrides.initialUserMessageChars : 100,
    fsSubagentAlwaysParentModel: overrides.fsSubagentAlwaysParentModel ?? null,
    fsPruningMode: overrides.fsPruningMode ?? null,
    fsPruningEnabled: overrides.fsPruningEnabled ?? null,
    fsExtensionToggles: overrides.fsExtensionToggles ?? {},
    fsToolResultPruningEnabled: overrides.fsToolResultPruningEnabled ?? null,
    fsToolResultPruningProfile: overrides.fsToolResultPruningProfile ?? null,
    sendCount: overrides.sendCount ?? 1,
    assistantTurnCount: overrides.assistantTurnCount ?? 1,
    assistantTurnDurationMs: overrides.assistantTurnDurationMs ?? 5000,
    busyDurationMs: overrides.busyDurationMs ?? 6000,
    busyPeriodCount: overrides.busyPeriodCount ?? 1,
    interruptedCount: overrides.interruptedCount ?? 0,
    messageEditCount: overrides.messageEditCount ?? 0,
    truncatedAfterCount: overrides.truncatedAfterCount ?? 0,
    backendErrorCount: overrides.backendErrorCount ?? 0,
    contextTokens: overrides.contextTokens ?? 10000,
    contextLimit: overrides.contextLimit ?? 100000,
    inputTokens: overrides.inputTokens ?? 1000,
    outputTokens: overrides.outputTokens ?? 500,
    cacheReadTokens: overrides.cacheReadTokens ?? 0,
    cacheWriteTokens: overrides.cacheWriteTokens ?? 0,
    tokenReportedTurnCount: overrides.tokenReportedTurnCount ?? 1,
    filesystemPathRefCount: overrides.filesystemPathRefCount ?? 0,
    imageInputCount: overrides.imageInputCount ?? 0,
    imageInputBytes: overrides.imageInputBytes ?? 0,
    unsupportedInputCount: overrides.unsupportedInputCount ?? 0,
    inputKindsUsed: overrides.inputKindsUsed ?? [],
    toolCallCount: overrides.toolCallCount ?? 0,
    toolDurationMs: overrides.toolDurationMs ?? 0,
    criticalPathDurationMs: overrides.criticalPathDurationMs ?? null,
    timedToolCallCount: overrides.timedToolCallCount ?? 0,
    toolFailureCount: overrides.toolFailureCount ?? 0,
    resultIssueCount: overrides.resultIssueCount ?? 0,
    subagentCallCount: overrides.subagentCallCount ?? 0,
    subagentTaskCount: overrides.subagentTaskCount ?? 0,
    subagentAgentCount: overrides.subagentAgentCount ?? 0,
    subagentInputTokens: overrides.subagentInputTokens ?? 0,
    subagentOutputTokens: overrides.subagentOutputTokens ?? 0,
    subagentCacheReadTokens: overrides.subagentCacheReadTokens ?? 0,
    subagentCacheWriteTokens: overrides.subagentCacheWriteTokens ?? 0,
    subagentEstimatedCostUsd: overrides.subagentEstimatedCostUsd ?? null,
    totalEstimatedCostUsd: overrides.totalEstimatedCostUsd ?? null,
    compactionCount: overrides.compactionCount ?? 0,
    autoRetryCount: overrides.autoRetryCount ?? 0,
    skillPruningPrepassInputTokens: overrides.skillPruningPrepassInputTokens ?? 0,
    skillPruningPrepassOutputTokens: overrides.skillPruningPrepassOutputTokens ?? 0,
    skillPruningPrepassCacheReadTokens: overrides.skillPruningPrepassCacheReadTokens ?? 0,
    skillPruningPrepassCacheWriteTokens: overrides.skillPruningPrepassCacheWriteTokens ?? 0,
    skillPruningPrepassDurationMs: overrides.skillPruningPrepassDurationMs ?? null,
    lastTurnInputTokens: overrides.lastTurnInputTokens ?? null,
    lastTurnOutputTokens: overrides.lastTurnOutputTokens ?? null,
    lastTurnCacheReadTokens: overrides.lastTurnCacheReadTokens ?? null,
    lastTurnCacheWriteTokens: overrides.lastTurnCacheWriteTokens ?? null,
    lastTurnTotalTokens: overrides.lastTurnTotalTokens ?? null,
    lastTurnReasoningTokens: overrides.lastTurnReasoningTokens ?? null,
    treatmentChangeKinds: overrides.treatmentChangeKinds ?? [],
    verificationTotalCount: overrides.verificationTotalCount ?? 0,
    verificationFailureCount: overrides.verificationFailureCount ?? 0,
    verificationState: overrides.verificationState ?? 'none',
    verificationCountBucket: overrides.verificationCountBucket ?? '0',
    verificationCountsByKind: overrides.verificationCountsByKind ?? { test: 0, build: 0, lint: 0, typecheck: 0, format: 0, other: 0 },
    fileWriteCount: overrides.fileWriteCount ?? 0,
    fileEditCount: overrides.fileEditCount ?? 0,
    fileDeleteCount: overrides.fileDeleteCount ?? 0,
    fileRenameCount: overrides.fileRenameCount ?? 0,
    touchedFileCount: overrides.touchedFileCount ?? 0,
    lineAdditions: overrides.lineAdditions ?? 0,
    lineDeletions: overrides.lineDeletions ?? 0,
    lineModifications: overrides.lineModifications ?? 0,
    lineMutationTotal: overrides.lineMutationTotal ?? 0,
    tokenEfficiency: overrides.tokenEfficiency ?? null,
    contextUtilization: overrides.contextUtilization ?? null,
    cacheHitRatio: overrides.cacheHitRatio ?? null,
    editRevisitRate: overrides.editRevisitRate ?? null,
    filesReviewedCount: overrides.filesReviewedCount ?? 0,
    readRevisitRate: overrides.readRevisitRate ?? null,
    estimatedCostUsd: overrides.estimatedCostUsd ?? null,
  };
}

const NO_REVIEWERS: ReviewerRuntimeReference[] = [];

/** Build a minimal PreparedSessionReviewV2Row joined to a run with a given qualityIndexV1. */
export function makeReview(
  run: PreparedRunRow,
  reviewId: string,
  qualityIndexV1: number | null,
  overrides: Partial<PreparedSessionReviewV2Row> = {},
): PreparedSessionReviewV2Row {
  return {
    cohort: 'v2_production',
    schemaVersion: 2,
    reviewId,
    sessionId: overrides.sessionId ?? run.sessionId,
    identityFallback: overrides.identityFallback ?? false,
    rubricVersion: 'session-review-v2.1',
    indexVersion: 'v1',
    reviewedAt: overrides.reviewedAt ?? '2026-07-24T10:00:00.000Z',
    startedDay: overrides.startedDay ?? '2026-07-24',
    joinKey: overrides.joinKey ?? 'session_id',
    unmatchedReason: overrides.unmatchedReason ?? null,
    runIds: overrides.runIds ?? [run.runId],
    modelFamilies: overrides.modelFamilies ?? [run.modelFamily!],
    criteria: overrides.criteria ?? [],
    attainment: overrides.attainment ?? {
      deliveredOverall: 'achieved',
      controllableOverall: 'achieved',
      core: { total: 1, assessable: 1, controllableDenominator: 1, met: 1, partlyMet: 0, unmet: 0, blocked: 0, externalBlocked: 0, notAssessable: 0, superseded: 0, deliveredRate: 1, controllableRate: 1 },
      supporting: { total: 0, assessable: 0, controllableDenominator: 0, met: 0, partlyMet: 0, unmet: 0, blocked: 0, externalBlocked: 0, notAssessable: 0, superseded: 0, deliveredRate: 0, controllableRate: 0 },
      optional: { total: 0, assessable: 0, controllableDenominator: 0, met: 0, partlyMet: 0, unmet: 0, blocked: 0, externalBlocked: 0, notAssessable: 0, superseded: 0, deliveredRate: 0, controllableRate: 0 },
      qualityIndexV1,
    },
    criterionCoverage: overrides.criterionCoverage ?? 1,
    externalBlockerRate: overrides.externalBlockerRate ?? 0,
    process: overrides.process ?? { requirementDiscipline: 'proportionate', verificationDiscipline: 'proportionate', scopeControl: 'controlled', recovery: 'not_needed', finalClaimAccuracy: 'accurate' },
    evidence: overrides.evidence ?? { requirements: 'clear', artifacts: 'direct', execution: 'direct', human: 'not_needed', limitations: [] },
    humanCheckStatus: overrides.humanCheckStatus ?? null,
    confidence: overrides.confidence ?? 'high',
    disagreement: overrides.disagreement ?? { material: false, adjudicated: false, disputedFields: [] },
    reviewers: overrides.reviewers ?? NO_REVIEWERS,
    diversityAchieved: overrides.diversityAchieved ?? false,
    blindingApplied: overrides.blindingApplied ?? true,
  };
}

/** Assemble a minimal PreparedAnalyticsData from runs + reviews (other channels empty). */
export function makePrepared(runs: PreparedRunRow[], reviews: PreparedSessionReviewV2Row[]): PreparedAnalyticsData {
  return {
    sourceSchemaVersion: 1,
    sourceExportedAt: '2026-07-24T10:00:00.000Z',
    sourceWorkspaceKey: 'test',
    runs,
    toolUsage: [],
    toolFailures: [],
    toolResultIssues: [],
    verificationUsage: [],
    backendErrors: [],
    fileExtensions: [],
    turnThroughput: [],
    retryTiming: [],
    pruningEvents: [],
    pruningSignals: [],
    toolResultPruning: [],
    warmBashRewrites: [],
    warmBashSummaries: [],
    sessionReviewsV2: reviews,
    sessionReviewV2Diagnostics: {
      rawProductionCount: reviews.length,
      acceptedCount: reviews.length,
      rejectedCount: 0,
      rejectedByReason: { unsupported_schema: 0, unsupported_rubric: 0, unsupported_index: 0, invalid_identity: 0, invalid_payload: 0 },
    },
    reviewJoinCoverage: {
      totalReviews: reviews.length,
      joinedCount: reviews.filter((review) => review.joinKey !== 'unmatched').length,
      unmatchedCount: reviews.filter((review) => review.joinKey === 'unmatched').length,
      byJoinKey: {
        session_id: reviews.filter((review) => review.joinKey === 'session_id').length,
        path_fallback: reviews.filter((review) => review.joinKey === 'path_fallback').length,
        unmatched: reviews.filter((review) => review.joinKey === 'unmatched').length,
      },
      unmatchedByReason: {
        no_run_for_identity: reviews.filter((review) => review.unmatchedReason === 'no_run_for_identity').length,
        identity_conflict_at_path: reviews.filter((review) => review.unmatchedReason === 'identity_conflict_at_path').length,
      },
    },
    historicalSessions: [],
  };
}
