-- Core per-run dataset for agent inspection.
SELECT
  run_id,
  task_group_id,
  started_at,
  status,
  model_id,
  model_family,
  thinking_level,
  experiment_assignment,
  mixed_model_config,
  mixed_treatment_config,
  initial_user_message_chars,
  context_file_count,
  filesystem_path_ref_count,
  image_input_count,
  tool_call_count,
  tool_duration_ms,
  critical_path_duration_ms,
  timed_tool_call_count,
  tool_failure_count,
  verification_total_count,
  verification_failure_count,
  busy_duration_ms,
  line_mutation_total,
  input_tokens,
  output_tokens,
  cache_read_tokens,
  cache_write_tokens,
  token_reported_turn_count,
  skill_pruning_prepass_duration_ms,
  estimated_cost_usd,
  subagent_estimated_cost_usd,
  total_estimated_cost_usd
FROM runs
ORDER BY started_at DESC;
