#!/usr/bin/env node
// scripts/sync-models.mjs — regenerate pie's derived model-config files from models.yaml.
//
// Source of truth: models.yaml (repo root) + models.schema.json.
// Derived (generated): models.json, model-profiles.yaml, and the model fields
// of settings.json (read-modify-write merge).
//
// Usage:
//   node scripts/sync-models.mjs           # validate + regenerate (write changed files)
//   node scripts/sync-models.mjs --check   # dry-run: exit 1 if any derived file would change
//   node scripts/sync-models.mjs --verbose # print what changed per file
//
// `yaml` and `ajv` are resolved from extension/node_modules (no root deps needed),
// mirroring the lazy-resolve pattern in extensions/subagent/bucket-selector.ts.

import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';

// --- repo root (from this script's location, NOT cwd) -----------------------

/** Repo root derived from this module's URL (works regardless of cwd). */
export function repoRoot() {
  return path.resolve(fileURLToPath(import.meta.url), '..', '..');
}

// --- lazy dependency resolution (yaml + ajv from extension/node_modules) ----

function buildResolver() {
  const baseRequire = createRequire(import.meta.url);
  const candidates = [baseRequire];
  try {
    candidates.push(createRequire(new URL('../extension/package.json', import.meta.url)));
  } catch {
    // extension package not resolvable from this environment
  }
  return candidates;
}

function resolveDep(name) {
  for (const req of buildResolver()) {
    try {
      return req(name);
    } catch {
      // try next candidate
    }
  }
  throw new Error(
    `Could not resolve "${name}" — run "npm install" in extension/ (yaml is a direct dep, ajv is transitive).`,
  );
}

let _yaml;
function getYaml() {
  if (!_yaml) _yaml = resolveDep('yaml');
  return _yaml;
}

let _Ajv;
function getAjv() {
  if (!_Ajv) {
    const mod = resolveDep('ajv');
    _Ajv = mod.default || mod.Ajv;
  }
  return _Ajv;
}

// --- banner ------------------------------------------------------------------

const BANNER = `# ⚠️  GENERATED by \`npm run sync-models\` from models.yaml — DO NOT EDIT.
# Source of truth: models.yaml (repo root). Edit there and re-run sync.
`;

// --- source loading + validation --------------------------------------------

/** Load and validate models.yaml. Returns the parsed source object. */
export function loadSource(root = repoRoot()) {
  const YAML = getYaml();
  const text = readFileSync(path.join(root, 'models.yaml'), 'utf8');
  const source = YAML.parse(text);

  const schema = JSON.parse(readFileSync(path.join(root, 'models.schema.json'), 'utf8'));
  const Ajv = getAjv();
  const validate = new Ajv({ allErrors: true, strict: false }).compile(schema);
  if (!validate(source)) {
    const errs = (validate.errors || [])
      .map((e) => `  at ${e.instancePath || '/'}: ${e.message ?? ''}`)
      .join('\n');
    throw new Error(`models.yaml schema validation failed:\n${errs}`);
  }

  validateExtra(source);
  return source;
}

/** Hand-written cross-field checks the JSON Schema can't easily express. */
function validateExtra(source) {
  const allIds = new Set();
  for (const [pname, provider] of Object.entries(source.providers)) {
    for (const m of provider.models) {
      if (allIds.has(m.id)) throw new Error(`duplicate model id across providers: ${m.id}`);
      allIds.add(m.id);
    }
  }

  const po = source.profileOrder;
  const poSet = new Set(po);
  if (poSet.size !== po.length) throw new Error('profileOrder has duplicate entries');
  for (const id of allIds) {
    if (!poSet.has(id)) throw new Error(`model '${id}' missing from profileOrder`);
  }
  for (const id of po) {
    if (!allIds.has(id)) throw new Error(`profileOrder references unknown model id '${id}'`);
  }
}

// --- generation -------------------------------------------------------------

const MJ_FIELD_ORDER = [
  'id',
  'name',
  'api',
  'compat',
  'reasoning',
  'family',
  'input',
  'contextWindow',
  'maxTokens',
  'thinkingLevelMap',
  'cost',
];

/** Build a models.json model object from a source model entry. */
function toModelsJsonModel(m, includeId) {
  const obj = {};
  for (const k of MJ_FIELD_ORDER) {
    if (k === 'id' && !includeId) continue;
    if (k === 'cost') {
      obj.cost = {
        input: m.pricing.input,
        output: m.pricing.output,
        cacheRead: m.pricing.cacheRead,
        cacheWrite: m.pricing.cacheWrite,
      };
    } else if (m[k] !== undefined) {
      obj[k] = m[k];
    }
  }
  return obj;
}

const PROVIDER_FIELD_ORDER = ['baseUrl', 'api', 'apiKey', 'compat', 'headers', 'concurrency', 'modelOverrides', 'models'];

/** Generate the models.json object (no banner — JSON cannot carry comments). */
export function generateModelsJson(source) {
  const providers = {};
  for (const [pname, provider] of Object.entries(source.providers)) {
    const out = {};
    for (const k of PROVIDER_FIELD_ORDER) {
      if (k === 'modelOverrides' || k === 'models') continue;
      if (provider[k] !== undefined) out[k] = provider[k];
    }
    const fullModels = [];
    const overrides = {};
    for (const m of provider.models) {
      if (m.overrideOnly) {
        overrides[m.id] = toModelsJsonModel(m, false);
      } else {
        fullModels.push(toModelsJsonModel(m, true));
      }
    }
    if (Object.keys(overrides).length > 0) out.modelOverrides = overrides;
    if (fullModels.length > 0) out.models = fullModels;
    providers[pname] = out;
  }
  return { providers };
}

/** Build a flat id → model map across all providers. */
function buildModelIndex(source) {
  const idx = new Map();
  for (const provider of Object.values(source.providers)) {
    for (const m of provider.models) idx.set(m.id, m);
  }
  return idx;
}

/** Generate model-profiles.yaml text (with banner). */
export function generateModelProfilesYaml(source) {
  const YAML = getYaml();
  const idx = buildModelIndex(source);
  const profiles = [];
  for (const id of source.profileOrder) {
    const m = idx.get(id);
    if (!m) throw new Error(`profileOrder references unknown model id '${id}'`);
    profiles.push({
      id: m.id,
      eligible: m.eligible,
      thinking: m.thinking,
      disabled_reason: m.disabledReason,
      cost: m.costRank,
    });
  }
  const body = YAML.stringify({ profiles }, { sortMapEntries: false, indent: 2 });
  return BANNER + body;
}

/** Read-modify-write merge of settings.json.
 *
 *  `defaultModel` / `defaultProvider` / `defaultThinkingLevel` are USER-OWNED:
 *  the running backend persists the user's selected model to settings.json, so
 *  sync only SEEDS them from models.yaml `defaults` when absent — it never
 *  clobbers a user's choice (which would reset the selected model on every
 *  `npm run sync-models`). `retry` and `pruning.{model,provider,thinkingLevel}`
 *  remain derived from models.yaml. The legacy `proxy` block (if still
 *  present from a previous version) is stripped — provider concurrency now
 *  lives in models.yaml `providers.<p>.concurrency`. */
export function generateSettings(source, existingSettings) {
  const s = JSON.parse(JSON.stringify(existingSettings));
  if (typeof s.defaultModel !== 'string' || s.defaultModel.length === 0) s.defaultModel = source.defaults.model;
  if (typeof s.defaultProvider !== 'string' || s.defaultProvider.length === 0) s.defaultProvider = source.defaults.provider;
  if (typeof s.defaultThinkingLevel !== 'string' || s.defaultThinkingLevel.length === 0) s.defaultThinkingLevel = source.defaults.thinkingLevel;
  s.retry = JSON.parse(JSON.stringify(source.retry));
  s.pruning = {
    ...(s.pruning && typeof s.pruning === 'object' ? s.pruning : {}),
    model: source.pruning.model,
    provider: source.pruning.provider,
    thinkingLevel: source.pruning.thinkingLevel,
  };
  // Strip legacy proxy block — replaced by host-side provider gate.
  delete s.proxy;
  return s;
}

/** Generate all derived outputs in memory. existingSettings is the parsed
 *  settings.json used as the merge base. */
export function generate(source, existingSettings) {
  return {
    modelsJson: generateModelsJson(source),
    modelProfilesYaml: generateModelProfilesYaml(source),
    settingsJson: generateSettings(source, existingSettings),
  };
}

/** Load source + existing settings.json, then generate all four outputs. */
export function loadAndGenerate(root = repoRoot()) {
  const source = loadSource(root);
  const existingSettings = JSON.parse(readFileSync(path.join(root, 'settings.json'), 'utf8'));
  return generate(source, existingSettings);
}

// --- check / write ----------------------------------------------------------

const DERIVED_PATHS = {
  modelsJson: 'models.json',
  modelProfilesYaml: 'model-profiles.yaml',
  settingsJson: 'settings.json',
};

/** Parse a derived file (JSON or YAML) into a JS value for semantic compare. */
function parseDerived(name, text) {
  if (name.endsWith('.json')) return JSON.parse(text);
  return getYaml().parse(text);
}

/** Pretty multi-line diff between two values (best-effort, for --verbose). */
function deepDiff(a, b, prefix = '') {
  const lines = [];
  if (a === b) return lines;
  if (typeof a !== typeof b || a === null || b === null) {
    if (JSON.stringify(a) !== JSON.stringify(b)) {
      lines.push(`${prefix}: ${JSON.stringify(a)} !== ${JSON.stringify(b)}`);
    }
    return lines;
  }
  if (Array.isArray(a) && Array.isArray(b)) {
    const n = Math.max(a.length, b.length);
    for (let i = 0; i < n; i++) {
      if (i >= a.length) lines.push(`${prefix}[${i}]: missing in generated, present in committed: ${JSON.stringify(b[i])}`);
      else if (i >= b.length) lines.push(`${prefix}[${i}]: present in generated, missing in committed: ${JSON.stringify(a[i])}`);
      else lines.push(...deepDiff(a[i], b[i], `${prefix}[${i}]`));
    }
    return lines;
  }
  if (typeof a === 'object' && typeof b === 'object') {
    const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
    for (const k of keys) {
      if (!(k in a)) lines.push(`${prefix}.${k}: missing in generated, present in committed: ${JSON.stringify(b[k])}`);
      else if (!(k in b)) lines.push(`${prefix}.${k}: present in generated, missing in committed: ${JSON.stringify(a[k])}`);
      else lines.push(...deepDiff(a[k], b[k], `${prefix}.${k}`));
    }
    return lines;
  }
  if (JSON.stringify(a) !== JSON.stringify(b)) {
    lines.push(`${prefix}: ${JSON.stringify(a)} !== ${JSON.stringify(b)}`);
  }
  return lines;
}

/** Run a dry-run check. Returns an array of {file, changed, diffLines}. */
export function check(root = repoRoot()) {
  const out = loadAndGenerate(root);
  const results = [];
  for (const [key, rel] of Object.entries(DERIVED_PATHS)) {
    const committed = parseDerived(rel, readFileSync(path.join(root, rel), 'utf8'));
    const generated =
      key === 'modelsJson' || key === 'settingsJson' ? out[key] : getYaml().parse(out[key]);
    let changed = false;
    let diffLines = [];
    try {
      assert.deepStrictEqual(generated, committed);
    } catch {
      changed = true;
      diffLines = deepDiff(generated, committed, key);
    }
    results.push({ file: rel, changed, diffLines });
  }
  return results;
}

/** Write a derived file (no-op if content unchanged). Returns true if written. */
function maybeWrite(root, rel, content) {
  const abs = path.join(root, rel);
  let existing = '';
  try {
    existing = readFileSync(abs, 'utf8');
  } catch {
    // file missing — write
  }
  if (existing === content) return false;
  writeFileSync(abs, content, 'utf8');
  return true;
}

/** Regenerate and write changed files. Returns array of {file, written}. */
export function sync(root = repoRoot()) {
  const out = loadAndGenerate(root);
  const results = [];
  const writes = [
    { key: 'modelsJson', rel: DERIVED_PATHS.modelsJson, serialize: (v) => JSON.stringify(v, null, 2) + '\n' },
    { key: 'modelProfilesYaml', rel: DERIVED_PATHS.modelProfilesYaml, serialize: (v) => v },
    { key: 'settingsJson', rel: DERIVED_PATHS.settingsJson, serialize: (v) => JSON.stringify(v, null, 2) + '\n' },
  ];
  for (const w of writes) {
    const content = w.serialize(out[w.key]);
    const written = maybeWrite(root, w.rel, content);
    results.push({ file: w.rel, written });
  }
  return results;
}

// --- CLI --------------------------------------------------------------------

function isMain() {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return path.resolve(entry) === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
}

function runCli() {
  const args = process.argv.slice(2);
  const checkMode = args.includes('--check');
  const verbose = args.includes('--verbose');
  const root = repoRoot();

  if (checkMode) {
    let results;
    try {
      results = check(root);
    } catch (err) {
      console.error(`sync-models: error: ${err.message}`);
      process.exit(2);
    }
    let anyChanged = false;
    for (const r of results) {
      if (r.changed) {
        anyChanged = true;
        console.error(`sync-models: DRIFT in ${r.file}`);
        if (verbose) {
          for (const line of r.diffLines) console.error(`  ${line}`);
        }
      } else if (verbose) {
        console.log(`sync-models: in sync: ${r.file}`);
      }
    }
    if (anyChanged) {
      if (!verbose) {
        console.error('sync-models: drift detected. Re-run with --verbose for details, or run `npm run sync-models` to regenerate.');
      }
      process.exit(1);
    }
    console.log('sync-models: all derived files in sync with models.yaml.');
    process.exit(0);
  }

  // write mode
  let results;
  try {
    results = sync(root);
  } catch (err) {
    console.error(`sync-models: error: ${err.message}`);
    process.exit(2);
  }
  for (const r of results) {
    console.log(`sync-models: ${r.written ? 'updated' : 'unchanged'} ${r.file}`);
  }
}

if (isMain()) {
  runCli();
}