#!/usr/bin/env node
// scripts/sync-models.mjs — regenerate pie's derived model-config files from models.yaml.
//
// Source of truth: models.yaml (repo root) + models.schema.json.
// Derived (generated): models.json, model-profiles.yaml, and the model fields
// of settings.json (read-modify-write merge).
//
// Usage:
//   node scripts/sync-models.mjs           # validate + regenerate (write changed files)
//   node scripts/sync-models.mjs --check   # dry-run: exit 1 if any derived file would change
//   node scripts/sync-models.mjs --verbose # print what changed per file
//
// `yaml` and `ajv` are resolved from extension/node_modules (no root deps needed),
// mirroring the lazy-resolve pattern in extensions/subagent/bucket-selector.ts.

import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';

// --- repo root (from this script's location, NOT cwd) -----------------------

/** Repo root derived from this module's URL (works regardless of cwd). */
export function repoRoot() {
  return path.resolve(fileURLToPath(import.meta.url), '..', '..');
}

// --- lazy dependency resolution (yaml + ajv from extension/node_modules) ----

function buildResolver() {
  const baseRequire = createRequire(import.meta.url);
  const candidates = [baseRequire];
  try {
    candidates.push(createRequire(new URL('../extension/package.json', import.meta.url)));
  } catch {
    // extension package not resolvable from this environment
  }
  return candidates;
}

function resolveDep(name) {
  for (const req of buildResolver()) {
    try {
      return req(name);
    } catch {
      // try next candidate
    }
  }
  throw new Error(
    `Could not resolve "${name}" — run "npm install" in extension/ (yaml and ajv are direct devDependencies of the extension).`,
  );
}

let _yaml;
function getYaml() {
  if (!_yaml) _yaml = resolveDep('yaml');
  return _yaml;
}

let _Ajv;
function getAjv() {
  if (!_Ajv) {
    const mod = resolveDep('ajv');
    _Ajv = mod.default || mod.Ajv;
  }
  return _Ajv;
}

// --- banner ------------------------------------------------------------------

const BANNER = `# ⚠️  GENERATED by \`npm run sync-models\` from models.yaml — DO NOT EDIT.
# Source of truth: models.yaml (repo root). Edit there and re-run sync.
`;

// --- source loading + validation --------------------------------------------

/** Load and validate models.yaml. Returns the parsed source object. */
export function loadSource(root = repoRoot()) {
  const YAML = getYaml();
  const text = readFileSync(path.join(root, 'models.yaml'), 'utf8');
  const source = YAML.parse(text);

  const schema = JSON.parse(readFileSync(path.join(root, 'models.schema.json'), 'utf8'));
  const Ajv = getAjv();
  const validate = new Ajv({ allErrors: true, strict: false }).compile(schema);
  if (!validate(source)) {
    const errs = (validate.errors || [])
      .map((e) => `  at ${e.instancePath || '/'}: ${e.message ?? ''}`)
      .join('\n');
    throw new Error(`models.yaml schema validation failed:\n${errs}`);
  }

  validateExtra(source);
  return source;
}

function identityKey(provider, id) {
  return JSON.stringify([provider, id]);
}

function profileRefKey(ref, providersById) {
  if (typeof ref === 'object' && ref !== null) return identityKey(ref.provider, ref.id);
  const providers = providersById.get(ref) ?? [];
  if (providers.length > 1) {
    throw new Error(`profileOrder model id '${ref}' is ambiguous; use { provider, id }`);
  }
  return providers.length === 1 ? identityKey(providers[0], ref) : undefined;
}

/** Validate the per-model image policy (see extensions/image-context-guard/README.md).
 *
 *  - A model whose `input` includes `image` MUST declare a positive integer
 *    `maxImagesPerRequest`. This includes `overrideOnly` entries: an override
 *    that claims image input must carry its own maximum rather than relying on
 *    the upstream built-in catalog (the SDK Model type does not retain this
 *    field, so the runtime image-context guard reads it from the generated
 *    catalog).
 *  - A text-only model (no `image` in `input`, or `input` absent) MUST NOT
 *    declare a positive `maxImagesPerRequest` — its effective maximum is zero.
 */
function validateImagePolicy(providerName, model) {
  const input = Array.isArray(model.input) ? model.input : [];
  const acceptsImages = input.includes('image');
  const hasMax = model.maxImagesPerRequest !== undefined;
  const identity = `${providerName}/${model.id}`;
  if (acceptsImages) {
    if (!hasMax) {
      throw new Error(
        `image-capable model '${identity}' must declare maxImagesPerRequest (positive integer)`,
      );
    }
    if (!Number.isInteger(model.maxImagesPerRequest) || model.maxImagesPerRequest < 1) {
      throw new Error(
        `model '${identity}' has invalid maxImagesPerRequest=${model.maxImagesPerRequest} (must be a positive integer)`,
      );
    }
  } else if (hasMax) {
    throw new Error(
      `text-only model '${identity}' must not declare maxImagesPerRequest (effective image maximum is zero)`,
    );
  }
}

/** Hand-written cross-field checks the JSON Schema can't easily express. */
function validateExtra(source) {
  const allModels = new Set();
  const providersById = new Map();
  for (const [providerName, provider] of Object.entries(source.providers)) {
    for (const model of provider.models) {
      const key = identityKey(providerName, model.id);
      if (allModels.has(key)) throw new Error(`duplicate model identity: ${providerName}/${model.id}`);
      allModels.add(key);
      const providers = providersById.get(model.id) ?? [];
      providers.push(providerName);
      providersById.set(model.id, providers);
      validateImagePolicy(providerName, model);
    }
  }

  const profileKeys = source.profileOrder.map((ref) => profileRefKey(ref, providersById));
  if (profileKeys.some((key) => key === undefined)) {
    const index = profileKeys.findIndex((key) => key === undefined);
    throw new Error(`profileOrder references unknown model '${JSON.stringify(source.profileOrder[index])}'`);
  }
  const profileSet = new Set(profileKeys);
  if (profileSet.size !== profileKeys.length) throw new Error('profileOrder has duplicate model identities');
  for (const key of allModels) {
    if (!profileSet.has(key)) {
      const [provider, id] = JSON.parse(key);
      throw new Error(`model '${provider}/${id}' missing from profileOrder`);
    }
  }

  // Historical/retired catalog: identities must be unique within the catalog,
  // and none may duplicate an active provider/id (a model still in `providers`
  // is not retired). Active pricing always wins; historical entries only fill
  // missing identities, so an active collision would be dead/misleading data.
  if (Array.isArray(source.historicalModels)) {
    const seenHistorical = new Set();
    for (const m of source.historicalModels) {
      const key = identityKey(m.provider, m.id);
      if (seenHistorical.has(key)) {
        throw new Error(`duplicate historical model identity: ${m.provider}/${m.id}`);
      }
      seenHistorical.add(key);
      if (allModels.has(key)) {
        throw new Error(`historical model '${m.provider}/${m.id}' is still active — remove it from historicalModels`);
      }
    }
  }
}

// --- generation -------------------------------------------------------------

const MJ_FIELD_ORDER = [
  'id',
  'name',
  'api',
  'compat',
  'reasoning',
  'family',
  'input',
  'maxImagesPerRequest',
  'contextWindow',
  'maxTokens',
  'thinkingLevelMap',
  'cost',
];

/** Build a models.json model object from a source model entry. */
function toModelsJsonModel(m, includeId) {
  const obj = {};
  for (const k of MJ_FIELD_ORDER) {
    if (k === 'id' && !includeId) continue;
    if (k === 'cost') {
      obj.cost = {
        input: m.pricing.input,
        output: m.pricing.output,
        cacheRead: m.pricing.cacheRead,
        cacheWrite: m.pricing.cacheWrite,
        ...(m.pricing.tiers !== undefined ? { tiers: m.pricing.tiers } : {}),
      };
    } else if (m[k] !== undefined) {
      obj[k] = m[k];
    }
  }
  return obj;
}

const PROVIDER_FIELD_ORDER = ['baseUrl', 'api', 'apiKey', 'compat', 'headers', 'concurrency', 'modelOverrides', 'models'];

/** Generate the models.json object (no banner — JSON cannot carry comments). */
export function generateModelsJson(source) {
  const providers = {};
  for (const [pname, provider] of Object.entries(source.providers)) {
    const out = {};
    for (const k of PROVIDER_FIELD_ORDER) {
      if (k === 'modelOverrides' || k === 'models') continue;
      if (provider[k] !== undefined) out[k] = provider[k];
    }
    const fullModels = [];
    const overrides = {};
    for (const m of provider.models) {
      if (m.overrideOnly) {
        overrides[m.id] = toModelsJsonModel(m, false);
      } else {
        fullModels.push(toModelsJsonModel(m, true));
      }
    }
    if (Object.keys(overrides).length > 0) out.modelOverrides = overrides;
    if (fullModels.length > 0) out.models = fullModels;
    providers[pname] = out;
  }
  return { providers };
}

/**
 * Generate the historical/retired model pricing catalog consumed by analysis
 * (`analysis/model-pricing-history.json`). Each entry mirrors the models.json
 * model shape (`cost` block) plus its `provider` so the analysis pricing/family
 * loaders can merge retired identities as a fallback behind active pricing.
 * Retired models are deliberately excluded from `models.json`, `profileOrder`,
 * and the picker — this file is read-only pricing/attribution metadata.
 */
export function generatePricingHistoryJson(source) {
  const entries = (source.historicalModels ?? []).map((m) => {
    const entry = {
      provider: m.provider,
      id: m.id,
      name: m.name,
      cost: {
        input: m.pricing.input,
        output: m.pricing.output,
        cacheRead: m.pricing.cacheRead,
        cacheWrite: m.pricing.cacheWrite,
        ...(m.pricing.tiers !== undefined ? { tiers: m.pricing.tiers } : {}),
      },
    };
    if (m.family !== undefined) entry.family = m.family;
    return entry;
  });
  return { models: entries };
}

/** Build full-identity and bare-id indexes for profile-order resolution. */
function buildModelIndex(source) {
  const byIdentity = new Map();
  const providersById = new Map();
  for (const [provider, config] of Object.entries(source.providers)) {
    for (const model of config.models) {
      byIdentity.set(identityKey(provider, model.id), { provider, model });
      const providers = providersById.get(model.id) ?? [];
      providers.push(provider);
      providersById.set(model.id, providers);
    }
  }
  return { byIdentity, providersById };
}

/** Generate model-profiles.yaml text (with banner). */
export function generateModelProfilesYaml(source) {
  const YAML = getYaml();
  const { byIdentity, providersById } = buildModelIndex(source);
  const profiles = [];
  for (const ref of source.profileOrder) {
    const key = profileRefKey(ref, providersById);
    const entry = key ? byIdentity.get(key) : undefined;
    if (!entry) throw new Error(`profileOrder references unknown model '${JSON.stringify(ref)}'`);
    const { provider, model } = entry;
    profiles.push({
      provider,
      id: model.id,
      eligible: model.eligible,
      thinking: model.thinking,
      disabled_reason: model.disabledReason,
      cost: model.costRank,
    });
  }
  const body = YAML.stringify({ profiles }, { sortMapEntries: false, indent: 2 });
  return BANNER + body;
}

/** Read-modify-write merge of settings.json.
 *
 *  Chat-model and pruning-model selections are USER-OWNED: the settings UI
 *  persists them to settings.json. Sync only SEEDS missing selections from
 *  models.yaml; it never clobbers an existing user choice. `retry` remains
 *  centrally derived. The legacy `proxy` block (if still present from a
 *  previous version) is stripped — provider concurrency now lives in
 *  models.yaml `providers.<p>.concurrency`. */
export function generateSettings(source, existingSettings) {
  const s = JSON.parse(JSON.stringify(existingSettings));
  const isNonEmptyString = (value) => typeof value === 'string' && value.length > 0;
  if (!isNonEmptyString(s.defaultModel)) s.defaultModel = source.defaults.model;
  if (!isNonEmptyString(s.defaultProvider)) s.defaultProvider = source.defaults.provider;
  if (!isNonEmptyString(s.defaultThinkingLevel)) s.defaultThinkingLevel = source.defaults.thinkingLevel;
  s.retry = JSON.parse(JSON.stringify(source.retry));

  const pruning = s.pruning && typeof s.pruning === 'object' ? s.pruning : {};
  if (!isNonEmptyString(pruning.model)) pruning.model = source.pruning.model;
  if (!isNonEmptyString(pruning.provider)) pruning.provider = source.pruning.provider;
  if (!isNonEmptyString(pruning.thinkingLevel)) pruning.thinkingLevel = source.pruning.thinkingLevel;
  s.pruning = pruning;

  // Strip legacy proxy block — replaced by host-side provider gate.
  delete s.proxy;
  return s;
}

/** Generate all derived outputs in memory. existingSettings is the parsed
 *  settings.json used as the merge base. */
export function generate(source, existingSettings) {
  return {
    modelsJson: generateModelsJson(source),
    modelProfilesYaml: generateModelProfilesYaml(source),
    settingsJson: generateSettings(source, existingSettings),
    pricingHistoryJson: generatePricingHistoryJson(source),
  };
}

/** Load source + existing settings.json, then generate all four outputs. */
export function loadAndGenerate(root = repoRoot()) {
  const source = loadSource(root);
  const existingSettings = JSON.parse(readFileSync(path.join(root, 'settings.json'), 'utf8'));
  return generate(source, existingSettings);
}

// --- check / write ----------------------------------------------------------

const DERIVED_PATHS = {
  modelsJson: 'models.json',
  modelProfilesYaml: 'model-profiles.yaml',
  settingsJson: 'settings.json',
  pricingHistoryJson: 'analysis/model-pricing-history.json',
};

/** Parse a derived file (JSON or YAML) into a JS value for semantic compare. */
function parseDerived(name, text) {
  if (name.endsWith('.json')) return JSON.parse(text);
  return getYaml().parse(text);
}

/** Pretty multi-line diff between two values (best-effort, for --verbose). */
function deepDiff(a, b, prefix = '') {
  const lines = [];
  if (a === b) return lines;
  if (typeof a !== typeof b || a === null || b === null) {
    if (JSON.stringify(a) !== JSON.stringify(b)) {
      lines.push(`${prefix}: ${JSON.stringify(a)} !== ${JSON.stringify(b)}`);
    }
    return lines;
  }
  if (Array.isArray(a) && Array.isArray(b)) {
    const n = Math.max(a.length, b.length);
    for (let i = 0; i < n; i++) {
      if (i >= a.length) lines.push(`${prefix}[${i}]: missing in generated, present in committed: ${JSON.stringify(b[i])}`);
      else if (i >= b.length) lines.push(`${prefix}[${i}]: present in generated, missing in committed: ${JSON.stringify(a[i])}`);
      else lines.push(...deepDiff(a[i], b[i], `${prefix}[${i}]`));
    }
    return lines;
  }
  if (typeof a === 'object' && typeof b === 'object') {
    const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
    for (const k of keys) {
      if (!(k in a)) lines.push(`${prefix}.${k}: missing in generated, present in committed: ${JSON.stringify(b[k])}`);
      else if (!(k in b)) lines.push(`${prefix}.${k}: present in generated, missing in committed: ${JSON.stringify(a[k])}`);
      else lines.push(...deepDiff(a[k], b[k], `${prefix}.${k}`));
    }
    return lines;
  }
  if (JSON.stringify(a) !== JSON.stringify(b)) {
    lines.push(`${prefix}: ${JSON.stringify(a)} !== ${JSON.stringify(b)}`);
  }
  return lines;
}

/** Run a dry-run check. Returns an array of {file, changed, diffLines}. */
export function check(root = repoRoot()) {
  const out = loadAndGenerate(root);
  const results = [];
  for (const [key, rel] of Object.entries(DERIVED_PATHS)) {
    const committed = parseDerived(rel, readFileSync(path.join(root, rel), 'utf8'));
    const generated =
      key === 'modelProfilesYaml' ? getYaml().parse(out[key]) : out[key];
    let changed = false;
    let diffLines = [];
    try {
      assert.deepStrictEqual(generated, committed);
    } catch {
      changed = true;
      diffLines = deepDiff(generated, committed, key);
    }
    // Trailing-newline check: caught by no parsed-JSON mechanism since both
    // parsed values are identical. Exclude settings.json because it is also a
    // runtime preference store and may be rewritten by pi while this check runs;
    // its formatting must not block commits or pushes.
    if (
      !changed &&
      key !== 'settingsJson' &&
      (rel.endsWith('.json') || rel.endsWith('.yaml'))
    ) {
      const committedRaw = readFileSync(path.join(root, rel), 'utf8');
      if (!committedRaw.endsWith('\n')) {
        changed = true;
        diffLines.push(
          `${key}: missing trailing newline (sync-models appends \\n)`,
        );
      }
    }
    results.push({ file: rel, changed, diffLines });
  }
  return results;
}

/** Write a derived file (no-op if content unchanged). Returns true if written. */
function maybeWrite(root, rel, content) {
  const abs = path.join(root, rel);
  let existing = '';
  try {
    existing = readFileSync(abs, 'utf8');
  } catch {
    // file missing — write
  }
  if (existing === content) return false;
  writeFileSync(abs, content, 'utf8');
  return true;
}

/** Regenerate and write changed files. Returns array of {file, written}. */
export function sync(root = repoRoot()) {
  const out = loadAndGenerate(root);
  const results = [];
  const writes = [
    { key: 'modelsJson', rel: DERIVED_PATHS.modelsJson, serialize: (v) => JSON.stringify(v, null, 2) + '\n' },
    { key: 'modelProfilesYaml', rel: DERIVED_PATHS.modelProfilesYaml, serialize: (v) => v },
    { key: 'settingsJson', rel: DERIVED_PATHS.settingsJson, serialize: (v) => JSON.stringify(v, null, 2) + '\n' },
    { key: 'pricingHistoryJson', rel: DERIVED_PATHS.pricingHistoryJson, serialize: (v) => JSON.stringify(v, null, 2) + '\n' },
  ];
  for (const w of writes) {
    const content = w.serialize(out[w.key]);
    const written = maybeWrite(root, w.rel, content);
    results.push({ file: w.rel, written });
  }
  return results;
}

// --- CLI --------------------------------------------------------------------

function isMain() {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return path.resolve(entry) === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
}

function runCli() {
  const args = process.argv.slice(2);
  const checkMode = args.includes('--check');
  const verbose = args.includes('--verbose');
  const root = repoRoot();

  if (checkMode) {
    let results;
    try {
      results = check(root);
    } catch (err) {
      console.error(`sync-models: error: ${err.message}`);
      process.exit(2);
    }
    let anyChanged = false;
    for (const r of results) {
      if (r.changed) {
        anyChanged = true;
        console.error(`sync-models: DRIFT in ${r.file}`);
        if (verbose) {
          for (const line of r.diffLines) console.error(`  ${line}`);
        }
      } else if (verbose) {
        console.log(`sync-models: in sync: ${r.file}`);
      }
    }
    if (anyChanged) {
      if (!verbose) {
        console.error('sync-models: drift detected. Re-run with --verbose for details, or run `npm run sync-models` to regenerate.');
      }
      process.exit(1);
    }
    console.log('sync-models: all derived files in sync with models.yaml.');
    process.exit(0);
  }

  // write mode
  let results;
  try {
    results = sync(root);
  } catch (err) {
    console.error(`sync-models: error: ${err.message}`);
    process.exit(2);
  }
  for (const r of results) {
    console.log(`sync-models: ${r.written ? 'updated' : 'unchanged'} ${r.file}`);
  }
}

if (isMain()) {
  runCli();
}